[platformio]
default_envs = ch32v003f4p6_wchsdk
src_dir = .

[env:ch32v003f4p6_wchsdk]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
board = genericCH32V003F4P6
framework = noneos-sdk
upload_protocol = wch-link
monitor_speed = 115200
extra_scripts = post:tools/export_bin.py

board_build.ldscript = Ld/Link.ld
board_build.startup = Startup/startup_ch32v00x.S
board_build.use_builtin_startup_file = no
board_build.use_builtin_system_code = no
board_build.use_builtin_debug_code = no

build_flags =
  -std=gnu99
  -IUser
  -IDebug
  -DNVIC_PriorityGroup_2=NVIC_PriorityGroup_1

build_src_filter =
  +<User/*.c>
  +<User/games/*.c>
  +<Debug/debug.c>
  -<User/games/pvd_test.c>
